apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: DB_HOST
              value: "inventory-postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "inventory_db"
            - name: DB_PORT
              value: "5432"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8080"
          ports:
            - containerPort: 3002

